### PR TITLE
Fix segfault for small max-socks

### LINKED ISSUE #791: Segmentation fault (core dumped) if set max-socks 11
There are some problems with max-socks setting.
1. There seems to be minimum value for eggdrop to work, which is not documented.
2. The error "Decreasing max-socks requires a restart" is misleading, when it is displayed for small value  (in my case 9) in eggdrop.conf and seems to be related to (1).
3. In my case setting max-socks exactly to 11 crashes eggdrop.

The bug was introduced when max-socks (and max_dcc) was introduced with commit 12cff4496d1bac1b3f6876a54590dc5c522de7ad

So, eggdrop versions affected: ~eggdrop 1.6.21 until current git 304a31c9556cc3b7649f8d18ac590e1247d51aa8 (Dec 4)

```
$ grep max-socks BotA.conf 
set max-socks 11
```

```
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.8.3+sendfprint (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
--- Loading eggdrop v1.8.3+sendfprint (Wed Dec  5 2018)
Listening for telnet connections on 0.0.0.0:3333 (all).
Module loaded: blowfish        
* Last context: tclhash.c/250 []
* Please REPORT this BUG!
* Check doc/BUG-REPORT on how to do so.
Segmentation fault (core dumped)
```

CFLAGS=O0 backtrace:

```
       Storage: /var/lib/systemd/coredump/core.eggdrop.1000.19c0c24ed447486a974b3bb8ed6cedcd.32152.1543981233000000.lz4
[...]
(gdb) bt full
#0  0x00007f70f0965130 in TclThreadAllocObj () from /usr/lib/libtcl8.6.so
No symbol table info available.
#1  0x00007f70f095bb52 in Tcl_NewStringObj () from /usr/lib/libtcl8.6.so
No symbol table info available.
#2  0x00007f70f094ac9e in TclSubstTokens () from /usr/lib/libtcl8.6.so
No symbol table info available.
#3  0x00007f70f087e8af in TclEvalEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#4  0x00007f70f087f153 in Tcl_EvalEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#5  0x00007f70f087f176 in Tcl_Eval () from /usr/lib/libtcl8.6.so
No symbol table info available.
#6  0x0000559d7b2beb16 in write_debug () at ./main.c:320
        x = 7
        s = "Wed Dec  5 04:40:33 2018"
        y = 994898064
#7  0x0000559d7b2beede in got_segv (z=11) at ./main.c:391
No locals.
#8  <signal handler called>
No symbol table info available.
#9  0x00007f70f0965130 in TclThreadAllocObj () from /usr/lib/libtcl8.6.so
No symbol table info available.
#10 0x00007f70f095bb52 in Tcl_NewStringObj () from /usr/lib/libtcl8.6.so
No symbol table info available.
#11 0x00007f70f0975ae4 in Tcl_SetVar2 () from /usr/lib/libtcl8.6.so
No symbol table info available.
#12 0x0000559d7b2db316 in check_tcl_log (lv=32, chan=0x559d7b2f702b "*", 
    msg=0x7ffd3b4cf58b "Module loaded: dns", ' ' <repeats 13 times>) at tclhash.c:1251
        mask = "* Module loaded: dns", ' ' <repeats 13 times>, '\000' <repeats 31 times>, "\001\000\000\000\000\000\000\000i:\227\360p\177\000\000\000\000\000\000\000\000\000\000\344\321\000\360p\177\000\000\320\032\220}\235U\000\000\000~\343n\275\035\000/\020\362L;\375\177\000\000\020\362L;\375\177\000\000\363\002\000\000\000\000\000\000P\261\216}\235U\000\000\330\363L;\375\177\000\000\000\204\225}\235U\000\000\213\365L;\375\177\000\000\306\332\374\357p\177\000\000\001\200\255\373\000\000\000\000\213\365L;\375\177\000\000\213\365L;\375\177\000\000"...
#13 0x0000559d7b2c4419 in putlog (arg1=32) at misc.c:570
        inhere = 1
        i = 3
        type = 32
        tsl = 11
        format = 0x559d7d8eb150 "Module loaded: %-16s"
        chname = 0x559d7b2f702b "*"
        s = "\220\365L;\375\177\000\000\000\000\000Module loaded: dns", ' ' <repeats 13 times>, "\000\360p\177\000\000\300\270\217}\235U\000\000\000\000\000\000\000\000\000\000\020\366L;\375\177\000\000\243\020\227\360p\177\000\000\030\254\225}\235U\000\000\270\271\217}\235U\000\000p\020\227\360p\177\000\000\260\227\221\360p\177\000\000`\361\236\360p\177\000\000\b\000\000\000\000\000\000\000\001\000\004\000\000\000\000\000\340\v\226}\235U\000\000\001\000\004\000\000\000\000\000\240ϐ}\235U\000\000\020:\220}\235U\000\000p\366L;\375\177\000\000\001\000\000\000\000\000\000\000\342\016\227\360p\177\000\000\001\000\000\000\000\000\000\000\300"...
        s1 = "\240ϐ}\235U\000\000\230\364L;\375\177\000\000\240\364L;\375\177\000\000\001\000\004\000\000\000\000\000\020\365L;\375\177\000\000\203\022\224\360p\177\000\000 \365L;\375\177\000\000\203\022\224\360p\177\000\000\020\365L;\375\177\000\000\340\v\226}\235U\000\000\300\270\217}\235U\000\000p\366L;\375\177\000\000x\366L;\375\177\000\000`\366L;\375\177\000\000\240ϐ}\235U\000\000\b\365L;\375\177\000\000\240ϐ}\235U\000\000\001\000\004\000\000\000\000\000 \365L;\375\177\000\000\000\000\000\000\310\000\000\000\000\365L;\375\177\000\000\000\000\000\000\310\000\000\000\200\365L;\375\177\000\000\240\n\226}\235U\000\000\300\270\217}\235U\000\000\340\366L"...
        out = 0x7ffd3b4cf58b "Module loaded: dns", ' ' <repeats 13 times>
        ct = "\270\365L;\375\177\000\000\240\365L;\375\177\000\000\240ϐ}\235U\000\000H\364L;\375\177\000\000\071\064.150.168.168:5`\364L;\375\177\000\000\000\000\000\000\310\000\000\000\000\000\217}\235U\000\000\000\366L;\375\177\000\000\b"
        s2 = 0x559d7d95accf "53"
        stamp = "[04:40:33] \000\000\000\000\000P\364L;\375\177\000\000@\v\226}\235U\000\000\300\270"
        va = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffd3b4cf960, reg_save_area = 0x7ffd3b4cf890}}
        now2 = 1543981233
        t = 0x7f70f0117300 <_tmbuf>
#14 0x0000559d7b2c8c16 in module_load (name=0x559d7d960120 "dns") at modules.c:832
        p = 0x559d7d96c170
        e = 0x0
        f = 0x7f70ef41172b <dns_start>
        workbuf = "dns_start\000ael/eggdrop/modules/dns.so\000h.so\000\224}\000\000\000\000\200\372L;\375\177\000\000\000~\343n\275\035\000/\001", '\000' <repeats 15 times>, " \222\224}\235U\000\000\000~\343n\275\035\000/\240\372L;\375\177\000\000\000\247\225}\235U", '\000' <repeats 18 times>, "\240ϐ}\235U\000\000 \222\224}\235U\000\000\000\000\000\000\000\000\000\000o%\227\360p\177\000\000\000\000\000\000\000\000\000\000\377\377\377\377", '\000' <repeats 13 times>, "~\343n\275\035\000/\300ɚ\360p\177\000\000\000\000\000\000\000\000\000\000"...
        hand = 0x559d7d8f5110
#15 0x0000559d7b2de495 in tcl_loadmodule (cd=0x0, irp=0x559d7d90cfa0, argc=2, argv=0x559d7d911490) at tclmisc.c:559
        p = 0x7f70f09054f1 <TclStackAlloc+49> "H\213U"
#16 0x00007f70f087792c in TclInvokeStringCommand () from /usr/lib/libtcl8.6.so
No symbol table info available.
#17 0x00007f70f087ca37 in TclNRRunCallbacks () from /usr/lib/libtcl8.6.so
No symbol table info available.
#18 0x00007f70f087ea68 in TclEvalEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#19 0x00007f70f0936c19 in Tcl_FSEvalFileEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#20 0x00007f70f0936dc9 in Tcl_EvalFile () from /usr/lib/libtcl8.6.so
No symbol table info available.
#21 0x0000559d7b2d17c6 in readtclprog (fname=0x559d7b30c720 <configfile> "BotA.conf") at tcl.c:768
        code = -1
        result = 0x0
        dstr = {string = 0x0, length = -268381724, spaceAvl = 32624, staticSpace = "\377\377\377\377", '\000' <repeats 21 times>, "\356\020\360p\177\000\000\000\000\000\000\000\000\000\000\240ϐ}\235U\000\000\000\000\000\000\000\000\000\000 \002M;\375\177\000\000\002\000\000\000\000\000\000\000\006\000\000\000\000\000\000\200", '\000' <repeats 48 times>, "\200I\021\360p\177\000\000r\000\000\000\000\000\000\000\320\177({\235U\000\000\340\004M;\375\177\000\000\000\000\000\000\000\000\000\000\004\325\372\357p\177\000\000\060\000\000\000\060\000\000\000\260\002M;\375\177\000\000\320\001M;\375\177\000"}
#22 0x0000559d7b29c3b3 in chanprog () at chanprog.c:463
        i = 5
#23 0x0000559d7b2c133a in main (arg_c=3, arg_v=0x7ffd3b4d04e8) at ./main.c:1157
        i = 16
        xx = 0
        s = "Wed Dec  5 2018\000:33 2018"
        f = 0x7f70f0a576c0
        sv = {__sigaction_handler = {sa_handler = 0x559d7b2beff9 <got_alarm>, sa_sigaction = 0x559d7b2beff9 <got_alarm>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x7ffd3b4d0420}
        chan = 0x0
        cdlim = {rlim_cur = 18446744073709551615, rlim_max = 18446744073709551615}
```

If i change position of "loadmodule dns" in eggdrop conf and place it one positon down, right after "loadmodule channel", i still get am error with dns mod but a slightly changed one:

```
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.8.3+sendfprint (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
--- Loading eggdrop v1.8.3+sendfprint (Wed Dec  5 2018)
Listening for telnet connections on 0.0.0.0:3333 (all).
Module loaded: blowfish        
Module loaded: channels        

TclNRExecuteByteCode: abnormal return at pc 3: stack top -15 < entry stack top 0
TclNRExecuteByteCode execution failure: end stack top < start stack top
Aborted (core dumped)
```

```
       Storage: /var/lib/systemd/coredump/core.eggdrop.1000.19c0c24ed447486a974b3bb8ed6cedcd.7899.1543985145000000.lz4
(gdb) bt full
#0  0x00007fec583eed7f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007fec583d9672 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007fec58daaf45 in Tcl_PanicVA () from /usr/lib/libtcl8.6.so
No symbol table info available.
#3  0x00007fec58dab00a in Tcl_Panic () from /usr/lib/libtcl8.6.so
No symbol table info available.
#4  0x00007fec58d6c0aa in TEBCresume () from /usr/lib/libtcl8.6.so
No symbol table info available.
#5  0x00007fec58cdfa37 in TclNRRunCallbacks () from /usr/lib/libtcl8.6.so
No symbol table info available.
#6  0x00007fec58ce002b in Tcl_ExprLongObj () from /usr/lib/libtcl8.6.so
No symbol table info available.
#7  0x00007fec58ce01bc in Tcl_ExprLong () from /usr/lib/libtcl8.6.so
No symbol table info available.
#8  0x00005633d3a9070a in tcl_eggint (cdata=0x5633d575d2d0, irp=0x5633d56c5fa0, name1=0x7fec5784716a "dns-cache", 
    name2=0x0, flags=32) at tcl.c:228
        s = 0x5633d5715a90 "86400"
        s1 = "ƀ\253\323\063V\000\000F\003\000\000\020\000\000\000\240\t\351\340\374\177\000\000\001\000\000\000\221\005\000\000\320\322u\325\063V\000"
        l = 140724081854832
        ii = 0x5633d575d2d0
#9  0x00005633d3a91cf4 in add_tcl_ints (list=0x7fec57849380 <dnsints>) at tcl.c:844
        i = 2
        tmp = 0
        ii = 0x5633d575d2d0
#10 0x00007fec578459e5 in dns_start (global_funcs=0x5633d3acca20 <global_table>) at .././dns.mod/dns.c:321
        idx = 1
#11 0x00005633d3a88b26 in module_load (name=0x5633d5719a20 "dns") at modules.c:820
        p = 0x5633d575cea0
        e = 0x0
        f = 0x7fec5784572b <dns_start>
        workbuf = "dns_start\000ael/eggdrop/modules/dns.so\000s.so\000p\325\000\000\000\000\000\v\351\340\374\177\000\000\000\302\332\325:\371F\254\001", '\000' <repeats 15 times>, " \"p\325\063V\000\000\000\302\332\325:\371F\254 \v\351\340\374\177\000\000\000\067q\325\063V", '\000' <repeats 18 times>, "\240_l\325\063V\000\000 \"p\325\063V\000\000\000\000\000\000\000\000\000\000oU\335X\354\177\000\000\000\000\000\000\000\000\000\000\377\377\377\377", '\000' <repeats 13 times>, "\302\332\325:\371F\254\300\371\340X\354\177\000\000\000\000\000\000\000\000\000\000"...
        hand = 0x5633d57261c0
#12 0x00005633d3a9e495 in tcl_loadmodule (cd=0x0, irp=0x5633d56c5fa0, argc=2, argv=0x5633d56ca490) at tclmisc.c:559
        p = 0x7fec58d684f1 <TclStackAlloc+49> "H\213U"
#13 0x00007fec58cda92c in TclInvokeStringCommand () from /usr/lib/libtcl8.6.so
No symbol table info available.
#14 0x00007fec58cdfa37 in TclNRRunCallbacks () from /usr/lib/libtcl8.6.so
No symbol table info available.
#15 0x00007fec58ce1a68 in TclEvalEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#16 0x00007fec58d99c19 in Tcl_FSEvalFileEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#17 0x00007fec58d99dc9 in Tcl_EvalFile () from /usr/lib/libtcl8.6.so
No symbol table info available.
#18 0x00005633d3a917c6 in readtclprog (fname=0x5633d3acc720 <configfile> "BotA.conf") at tcl.c:768
        code = -1
        result = 0x0
        dstr = {string = 0x0, length = 1481048548, spaceAvl = 32748, 
          staticSpace = "\377\377\377\377", '\000' <repeats 21 times>, "\036WX\354\177\000\000\000\000\000\000\000\000\000\000\240_l\325\063V\000\000\000\000\000\000\000\000\000\000\240\022\351\340\374\177\000\000\002\000\000\000\000\000\000\000\006\000\000\000\000\000\000\200", '\000' <repeats 48 times>, "\200yWX\354\177\000\000r\000\000\000\000\000\000\000\320\177\244\323\063V\000\000`\025\351\340\374\177\000\000\000\000\000\000\000\000\000\000\004\005AX\354\177\000\000\060\000\000\000\060\000\000\000\060\023\351\340\374\177\000\000P\022\351\340\374\177\000"}
#19 0x00005633d3a5c3b3 in chanprog () at chanprog.c:463
        i = 5
#20 0x00005633d3a8133a in main (arg_c=3, arg_v=0x7ffce0e91568) at ./main.c:1157
        i = 16
        xx = 0
        s = "Wed Dec  5 2018\000:45 2018"
        f = 0x7fec58eba6c0
        sv = {__sigaction_handler = {sa_handler = 0x5633d3a7eff9 <got_alarm>, 
            sa_sigaction = 0x5633d3a7eff9 <got_alarm>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, 
          sa_restorer = 0x7ffce0e914a0}
        chan = 0x0
        cdlim = {rlim_cur = 18446744073709551615, rlim_max = 18446744073709551615}
```

It has something todo with the call to new_dcc(). If i return NULL before the call to new_dcc() in line https://github.com/eggheads/eggdrop/blob/develop/src/mod/dns.mod/dns.c#L300 it doesn't crash. If i return NULL right after the call to new_dcc() it crashes.

Eggdrop crashes also when `"loadmodule dns"` is the last line in eggdrop config.

Eggdrop dosn't crash, if "loadmodule dns" is commented out in eggdrop config and after `"./eggdrop -nt"` `".loadmod dns"` is executed.

OK, it **does** crash... only... much later... see the following log, for which i inserted some DEBUG prints to see when new_dcc() is called and which values it returns:

```
$ grep max-socks BotA.conf 
set max-socks 11
```

```
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.8.3+sendfprint (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
--- Loading eggdrop v1.8.3+sendfprint (Wed Dec  5 2018)
DEBUG: new_dcc() 0
Listening for telnet connections on 0.0.0.0:3333 (all).
Module loaded: blowfish        
Module loaded: channels        
Module loaded: server          
Module loaded: ctcp            
Module loaded: irc             
Module loaded: notes            (with lang support)
Module loaded: console          (with lang support)
Module loaded: uptime          
Loading dccwhois.tcl...
Loaded dccwhois.tcl
Userinfo TCL v1.07 loaded (URL BF GF IRL EMAIL DOB PHONE ICQ).
use '.help userinfo' for commands.
Writing channel file...
Userfile loaded, unpacking...
=== BotA: 0 channels, 5 users.
DEBUG: new_dcc() 1
DEBUG: main(): term_z = 1

### ENTERING DCC CHAT SIMULATION ###
[...]
*** -HQ joined the party line.
[06:51:37] main: entering loop
DEBUG: new_dcc() 2
[06:51:38] triggering bind quotepong_bind
[06:51:38] triggered bind quotepong_bind, user 0.046ms sys 0.006ms
[06:51:38] Trying server [127.0.0.1]:6667
[06:51:38] net: attempted socket connection refused: 127.0.0.1:6667
[06:51:38] Failed connect to 127.0.0.1 (Operation now in progress)
[06:51:38] net: connect! sock 7
[06:51:38] Connected to 127.0.0.1
[06:51:38] net: eof!(read) socket 7
[06:51:38] Disconnected from 127.0.0.1
.loadmod dns
[06:51:43] tcl: builtin dcc call: *dcc:loadmod -HQ 1 dns
DEBUG: new_dcc() 3
DEBUG: dns_start(): idx = 3
[06:51:43] Module loaded: dns             
[06:51:43] #-HQ# loadmod dns
Module loaded: dns             

DEBUG: new_dcc() 4
[06:52:38] triggering bind quotepong_bind
[06:52:38] triggered bind quotepong_bind, user 0.029ms sys 0.004ms
[06:52:38] Trying server [127.0.0.1]:6667
[06:52:38] net: attempted socket connection refused: 127.0.0.1:6667
[06:52:38] Failed connect to 127.0.0.1 (Operation now in progress)
[06:52:38] net: connect! sock 8
[06:52:38] Connected to 127.0.0.1
[06:52:38] net: eof!(read) socket 8
[06:52:38] Disconnected from 127.0.0.1
DEBUG: new_dcc() 5
[...]
((( after a lots of intended failed connection attempts ... )))
[08:12:43] triggering bind quotepong_bind
[08:12:43] triggered bind quotepong_bind, user 0.024ms sys 0.009ms
[08:12:43] Trying server [127.0.0.1]:6667
[08:12:43] net: attempted socket connection refused: 127.0.0.1:6667
[08:12:43] Failed connect to 127.0.0.1 (Operation now in progress)
[08:12:43] net: connect! sock 8
[08:12:43] Connected to 127.0.0.1
[08:12:43] net: eof!(read) socket 8
[08:12:43] Disconnected from 127.0.0.1
DEBUG: new_dcc() 85
Segmentation fault (core dumped)
```

```
[...]
       Storage: /var/lib/systemd/coredump/core.eggdrop.1000.19c0c24ed447486a974b3bb8ed6cedcd.29444.1543994023000000.lz4
[...]
(gdb) bt full
#0  0x00007f14a2ac1a09 in TclLookupSimpleVar () from /usr/lib/libtcl8.6.so
No symbol table info available.
#1  0x00007f14a2ac25da in TclObjLookupVarEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#2  0x00007f14a2ac37ff in Tcl_ObjSetVar2 () from /usr/lib/libtcl8.6.so
No symbol table info available.
#3  0x00007f14a2ac3a4c in Tcl_SetVar2Ex () from /usr/lib/libtcl8.6.so
No symbol table info available.
#4  0x00007f14a2ac3af9 in Tcl_SetVar2 () from /usr/lib/libtcl8.6.so
No symbol table info available.
#5  0x000055faadceb2fb in check_tcl_log (lv=32, chan=0x55faadd0599b "*", 
    msg=0x7ffed37e7c3b "* Last context: tclhash.c/749 []") at tclhash.c:1249
        mask = "* * Last context: tclhash.c/749 []\000\323\376\177\000\000'\000\000\000\000\000\000\000x\177~\323\376\177\000\000\334kЭ\372U\000\000\000\316%\242\024\177\000\000\363.\017\242\024\177\000\000\000\000\000\000\000\000\000\000\344\261\025\242\024\177\000\000\377\377\377\377\377\067\064\071\000\005\351\332?W\277\225\300x~\323\376\177\000\000\300x~\323\376\177\000\000\363\002\000\000\000\000\000\000YZЭ\372U\000\000\210z~\323\376\177\000\000\240\017\372\257\372U\000\000;|~\323\376\177\000\000ƺ\021\242\024\177\000\000\001\200\255\373\376\177\000\000;|~\323\376\177\000\000;|~\323\376\177\000\000;|~"...
#6  0x000055faadcd4454 in putlog (arg1=32) at misc.c:570
        inhere = 1
        i = 32532
        type = 32
        tsl = 11
        format = 0x55faadd05a59 "* Last context: %s/%d [%s]"
        chname = 0x55faadd0599b "*"
        s = "\240\267\005\260\372U\000\000\240\017\372* Last context: tclhash.c/749 []\000\000\000\000\000\320\000\376\257\372U\000\000\240\017\372\257\372U\000\000\200\306\375\257\372U\000\000\000\000\000\000\000\000\000\000\300\251\257\242\024\177\000\000\020", '\000' <repeats 23 times>, "\200\306\375\257\372U\000\000\000\005\351\332?W\277\225\240\017\372\257\372U\000\000llama@co }~\323\376\177\000\000\320\177ɭ\372U\000\000 \220~\323\376\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\201\061ͭ\372U\000\000\001\000\000\000\000\000\000\000`\346"...
        s1 = "\332kЭ\372U\000\000\030\000\000\000\060\000\000\000 \200~\323\376\177\000\000`\177~\323\376\177\000\000[08:12:43] net: eof!(read) socket 8\n\000\177\000\000\030\000\000\000\060\000\000\000 \202~\323\376\177\000\000`\201~\323\376\177\000\000P|~\323\376\177\000\000\071\062\253\242\024\177\000\000\240\267\005\260\372U\000\000o\375\253\242\024\177\000\000\240\017\372\257\372U\000\000\000\000\000\000\000\000\000\000@\362\004\260\372U\000\000\320\000\376\257\372U\000\000\000\000\000\000gere@!\376\257\372U\000\000\300\251\257\242\024\177\000\000\b\000\000\000\000\000\000\000\200\306\375\257\372U\000\000\000\000\000\000\000\000\000\000"...
        out = 0x7ffed37e7c3b "* Last context: tclhash.c/749 []"
        ct = "\000\000\000\000\000\000\000\000\300\305%\242\024\177\000\000h\r\000\000\000\000\000\000\223\221Э\372U\000\000\000\000\000\000\000\000\000\000\223\221Э\372U\000\000\020\200~\323\376\177\000\000\230\221Э\372U\000\000\300\370\370\257\372U\000\000\000\000\000\000\001\000\000\000\001"
        s2 = 0x7f14a2abf0a3 <CompareVarKeys+51> "\205\300\017\224\300\017\266\300[]A\\\303H\211\337\377\025'9\b"
        stamp = "[08:13:43] \000\372U\000\000\000\000\000\000\376\177\000\000k\206~\323\376\177\000\000\000"
        va = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffed37e8010, reg_save_area = 0x7ffed37e7f40}}
        now2 = 1543994023
        t = 0x7f14a2265300 <_tmbuf>
#7  0x000055faadccea29 in write_debug () at ./main.c:298
        x = 22010
        s = "\300\251\257\242\024\177\000\000\000\000\000\000\000\000\000\000\060\031\376\257\372U\000\000"
        y = -1342297200
#8  0x000055faadccef00 in got_segv (z=11) at ./main.c:391
No locals.
#9  <signal handler called>
No symbol table info available.
#10 0x00007f14a2ac1a09 in TclLookupSimpleVar () from /usr/lib/libtcl8.6.so
No symbol table info available.
#11 0x00007f14a2ac25da in TclObjLookupVarEx () from /usr/lib/libtcl8.6.so
No symbol table info available.
#12 0x00007f14a2ac37ff in Tcl_ObjSetVar2 () from /usr/lib/libtcl8.6.so
No symbol table info available.
#13 0x00007f14a2ac3a4c in Tcl_SetVar2Ex () from /usr/lib/libtcl8.6.so
No symbol table info available.
#14 0x00007f14a2ac3af9 in Tcl_SetVar2 () from /usr/lib/libtcl8.6.so
No symbol table info available.
#15 0x000055faadceb179 in check_tcl_event (event=0x7f14a2b6b8ab "connect-server") at tclhash.c:1223
No locals.
#16 0x00007f14a2b5f0dc in connect_server () at .././server.mod/servmsg.c:1224
        chan = 0x55fab005ba20
        x = 0x55fab0039340
        pass = "\000+\376\257\372U\000\000\r\020\254\242\024\177\000\000\060\031\376\257\372U\000\000\000\005\351\332\000\000\000\000\260\035\376\257\372U\000\000\240\017\372\257\372U\000\000\060\031\376\257\372U\000\000\000\000\000\000\000\000\000\000\300\251\257\242\024\177\000\000\b", '\000' <repeats 23 times>, "\060\031\376\257\372U\000\000\000\005\351\332?W\277\225\240\017\372\257\372U\000\000l"
        botserver = "@\211~\323\376\177\000\000\320\177ɭ\372U\000\000 \220~\323\376\177", '\000' <repeats 18 times>, "--Type <RET> for more, q to quit, c to continue without paging--c
\201\061ͭ\372U\000\000\356\212Э\372U\000\000\274\003\000\000\306\003\000\000\356\212Э\372U\000\000\320\064\253\242\024\177\000\000llama@co\257$\253\242\024\177\000\000llama@cop\211~\323\376\177\000\000\320\177ɭ\372U\000\000V\021έ\372U\000\000\v\262\266\242\024\177\000\000 \304\370\257\372U\000\000`\212~\323\376\177\000\000\b\352ͭ\372U\000\000a\261\266\242\024\177\000\000\v\000\000\000\372U", '\000' <repeats 14 times>, "@\212~\323 Aͭ\372U\000\000\257$\253\242\024\177\000\000\000\000\000\000\000\000\000\000"...
        servidx = 85
        botserverport = 0
#17 0x00007f14a2b6866e in server_secondly () at .././server.mod/server.c:1667
No locals.
#18 0x000055faadcd020f in mainloop (toplevel=1) at ./main.c:836
        p = 0x55fab00391d0
        pn = 0x0
        socket_cleanup = 0
        xx = -3
        i = 0
        eggbusy = 1
        tclbusy = 0
        buf = "\000loadmod\000dns\000\000\000\000\060\020\376\257\372U\000\000\200\030\372\257\372U", '\000' <repeats 26 times>, "\373\063\251\242\024\177\000\000\200\346\376\257\372U\000\000\240\017\372\257\372U\000\000 \005\376\257\372U\000\000\r\020\254\242\024\177\000\000\060\031\376\257\372U\000\000\000\005\351\332", '\000' <repeats 12 times>, "\240\017\372\257\372U\000\000\060\031\376\257\372U\000\000\000\000\000\000\000\000\000\000\300\251\257\242\024\177\000\000\b", '\000' <repeats 23 times>, "\060\031\376\257\372U\000\000\000\005\351\332?W\277\225\240\017\372\257\372U\000\000"...
#19 0x000055faadcd1ad3 in main (arg_c=3, arg_v=0x7ffed37e9028) at ./main.c:1287
        i = -1
        xx = 29444
        s = "29442\n\000  5 2018\000:37 2018"
        f = 0x55faaff82e80
        sv = {__sigaction_handler = {sa_handler = 0x55faadccf01b <got_alarm>, sa_sigaction = 0x55faadccf01b <got_alarm>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x7ffed37e8f60}
        chan = 0x0
        cdlim = {rlim_cur = 18446744073709551615, rlim_max = 18446744073709551615}
```

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by:
Patch by:
Fixes: #791 

One-line summary:
Fix segfault for small max-socks

Additional description (if needed):
Eggdrop increases dcc table in amounts of 10 entries per increase with upper limit max-socks. It distinguishes between socket and dcc and tries to keep max_dcc = MAXSOCKS - 10.
See https://github.com/eggheads/eggdrop/blob/develop/src/dccutil.c#L82
The whole dcc table increase handling looks ugly. Why is is increasing in amounts of 10 entries per increase? Why is it keeping max_dcc below MAXSOCKS, i mean why exactly 10 below , and why is new_dcc() counting up every time it is called? If eggdrop tries to connect to irc server and every time it does, it increases the dcc value, it will hit that max-socks soon. If you don't change max-socks, after about 100 connects it will fail to try again with:
```
[04:06:47] NO MORE DCC CONNECTIONS -- Can't create server connection.
[04:06:48] Maximum socket limit reached. Consider raising max-socks.
```
This would make sense in that you don't want to go higher than max-socks. But: Eggdrop doesn't really use dcc/socks here, it just wastes them. and the dcc table grows with empty entries. Every failed connection will count against sock-max. Something should be done about that. I don't think this is intended.
There is also repeated code in eggdrop like:
```
if (dcc_total == max_dcc && increase_socks_max())
[...]
i = new_dcc()
```
This code wantes some improvement. I mean: new_dcc() is already doing this check and increase.

**Anywayz, this patch fixes the segfault by properly handling max_dcc. Lets merge it as is.**

Test cases demonstrating functionality (if applicable):
```
$ grep max-socks BotA.conf
set max-socks 11
```

Before:
```
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.8.3+sendfprint (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
--- Loading eggdrop v1.8.3+sendfprint (Thu Dec  6 2018)
Listening for telnet connections on 0.0.0.0:3333 (all).
Module loaded: blowfish        
* Last context: tclhash.c/250 []
* Please REPORT this BUG!
* Check doc/BUG-REPORT on how to do so.
Segmentation fault (core dumped)
```

After:
```
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.8.3+sendfprint (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
--- Loading eggdrop v1.8.3+sendfprint (Thu Dec  6 2018)
Listening for telnet connections on 0.0.0.0:3333 (all).
Module loaded: blowfish        
Maximum dcc limit reached. Consider raising max-socks.
Can't load modules dns: NO MORE DCC CONNECTIONS -- Can't create DNS socket.
Module loaded: channels        
Module loaded: server          
Module loaded: ctcp            
Module loaded: irc             
Module loaded: notes            (with lang support)
Module loaded: console          (with lang support)
Module loaded: uptime          
Loading dccwhois.tcl...
Loaded dccwhois.tcl
Userinfo TCL v1.07 loaded (URL BF GF IRL EMAIL DOB PHONE ICQ).
use '.help userinfo' for commands.
Writing channel file...
Userfile loaded, unpacking...
=== BotA: 0 channels, 5 users.
[04:14:52] * ERROR: Failed to initialize foreground chat.
```

### CODE REVIEW

**Comment by thommey** [comment]
This is definitely broken. The only reason I can see is that starting at 10 for max-socks (which is dcc + tcl sockets) breaks Tcl, it needs some room to start (stdin, stdout, stderr to begin with). And the only reason I can see why max_dcc is starting at 0 is to malloc() instead of realloc() on the first one. This can be solved different, but in general, the conclusion is that this variable should be removed completely. The autoresizing should continue indefinitely until FD_MAX (whatever select()s limit is, or the ulimit).

I don't know max-dcc existed before max-socks to limit partyline connections but I can guess to prevent abuse. This could be solved with: 1) a limit on pending unauthenticated connections (before username/password), and 2) a limit on concurrent authenticated connections per username. Then we can remove max-socks (which should not be exposed to users at that level)

**Comment by michaelortmann** [comment]
Yes Yes Yes! But lets do it with another Issue/PR and fix the possible segfault here and now.

**Comment by Cizzle** [comment]
You are wrong with:
> This would make sense in that you don't want to go higher than max-socks. But: Eggdrop doesn't really use dcc/socks here, it just wastes them. and the dcc table grows with empty entries. Every failed connection will count against sock-max. Something should be done about that. I don't think this is intended.

There are no empty entries, they are first marked as `DCC_LOST` and then cleared at a later time (every 5 ticks) (see `lostdcc()` and `dcc_remove_lost()`).

There are 10 socks saved for Tcl usage, so when setting `max-socks` one should keep in mind at least 10 can not be used for DCC.

File: src/dccutil.c [hunk 1]
```diff
@@ -79,9 +79,17 @@ int increase_socks_max()
...
 
   if (td->mainthread) {
-    max_dcc = td->MAXSOCKS - 10;
-    if (max_dcc < 1)
-      max_dcc = 1;
+    max_dcc_new = td->MAXSOCKS - 10;
+    if (max_dcc_new > max_dcc)
+      max_dcc = max_dcc_new;
+    else {
+      if (max_dcc == 0)
```
Comment (Cizzle) [inline src/dccutil.c]: Combine please.

**Comment by michaelortmann** [comment]
@Cizzle: You're right, the text block is obsolete, i messed up something while testing.

File: src/dccutil.c (hunk 1 above)
Comment (michaelortmann) [reply src/dccutil.c]: Done.

**Comment by Cizzle** [comment]
LGTM
