### PR TITLE
Fix nat-ip bug

### LINKED ISSUE #1181: Nat-ip returns 255.255.255.255 with invalid input
Found by: Fatale_gg

A user entered with ctcp chat issues after setting config file variable 'nat-ip' to a hostname. While the config file does state it takes an IP, at minimum an error should be thrown for invalid input. The specific issue results from using inet_addr (from the man page):

> The inet_addr() function converts the Internet host address cp from IPv4 numbers-and-dots notation into binary data in network byte order. If the input is invalid, INADDR_NONE (usually -1) is returned. Use of this function is problematic because -1 is a valid address (255.255.255.255). Avoid its use in favor of inet_aton(), inet_pton(3), or getaddrinfo(3) which provide a cleaner way to indicate error return. 

The task at minimum  here is to update from inet_addr to something more modern. Discussion could occur as to whether or not this setting should be upgraded to resolve a hostname- as a scenario:

A user on a home network is more likely to be NAT'd than a cloud/colo server. A home user is also more likely to on a dynamic IP rather than a static. A user may setup a dyndns-like service that is updated with the correct dynamic IP, and then try to use that hostname with nat-ip, so Eggdrop sends a proper IP after the IP changes.

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: Fatale_gg
Patch by: michaelortmann
Fixes: #1181

One-line summary:

Additional description (if needed):

Test cases demonstrating functionality (if applicable):
**Test1:**
eggdrop.conf:
`#set nat-ip`
```
/ctcp BotA chat
*** DCC CHAT (chat) request received from BotA [127.0.0.1:3333]
```
**Test2:**
`set nat-ip ""`
```
/ctcp BotA chat
*** DCC CHAT (chat) request received from BotA [127.0.0.1:3333]
```
**Test3:**
eggdrop.conf:
`set nat-ip "192.168.42.1"`
```
/ctcp BotA chat
*** DCC CHAT (chat) request received from BotA [192.168.42.1:3333]
```
```
.set nat-ip 192.168.23.1
[12:25:52] tcl: builtin dcc call: *dcc:set -HQ 1 nat-ip 192.168.23.1
[12:25:52] #-HQ# set nat-ip 192.168.23.1
Ok, set.
.set nat-ip
[12:26:45] tcl: builtin dcc call: *dcc:set -HQ 1 nat-ip
[12:26:45] #-HQ# set nat-ip
Currently: 192.168.23.1
.set nat-ip test
[12:27:08] tcl: builtin dcc call: *dcc:set -HQ 1 nat-ip test
[12:27:08] #-HQ# set nat-ip test
Error: can't set "nat-ip": address was not parseable in AF_INET
.set nat-ip
[12:27:12] tcl: builtin dcc call: *dcc:set -HQ 1 nat-ip
[12:27:12] #-HQ# set nat-ip
Currently: 192.168.23.1
```
**Test4:**
eggdrop.conf:
`set nat-ip "test"`
```
$ ./eggdrop -t BotA.conf 

Eggdrop v1.9.1+monitor (C) 1997 Robey Pointer (C) 1999-2021 Eggheads
--- Loading eggdrop v1.9.1+monitor (Sun Oct 31 2021)
* ERROR: config file: nat-ip address was not parseable in AF_INET
```
**Test5:**
```
$ ./configure --disable-ipv6
[...]
$ ./eggdrop -v
Eggdrop v1.9.1+monitor (C) 1997 Robey Pointer (C) 1999-2021 Eggheads
Configure flags: '--disable-ipv6'
Compiled with: TLS, handlen=32
```
eggdrop.conf:
`#set nat-ip`
```
/ctcp BotA chat
*** DCC CHAT (chat) request received from BotA [127.0.0.1:3333]
```

### CODE REVIEW

File: src/net.c [hunk 1]
```diff
@@ -784,22 +786,29 @@ int getdccfamilyaddr(sockname_t *addr, char *s, size_t l, int restrict_af)
...
       inet_ntop(AF_INET6, &r->addr.s6.sin6_addr, s, l);
   } else
 #endif
-  egg_snprintf(s, l, "%lu", natip[0] ? iptolong(inet_addr(natip)) :
-             ntohl(r->addr.s4.sin_addr.s_addr));
+  {
+    if (*nat_ip_string)
+      strlcpy(s, nat_ip_string, l);
+    else
+      snprintf(s, l, "%u", ntohl(r->addr.s4.sin_addr.s_addr));
```
Comment (thommey) [inline src/net.c]: should be "%" PRIu32

File: src/net.c [hunk 2]
```diff
@@ -784,22 +786,29 @@ int getdccfamilyaddr(sockname_t *addr, char *s, size_t l, int restrict_af)
...
     if (IN6_IS_ADDR_V4MAPPED(&r->addr.s6.sin6_addr) ||
         IN6_IS_ADDR_UNSPECIFIED(&r->addr.s6.sin6_addr)) {
-      memcpy(&ip, r->addr.s6.sin6_addr.s6_addr + 12, sizeof ip);
-      egg_snprintf(s, l, "%lu", natip[0] ? iptolong(inet_addr(natip)) :
-               ntohl(ip));
+      if (*nat_ip_string)
+        strlcpy(s, nat_ip_string, l);
+      else {
+        memcpy(&ip, r->addr.s6.sin6_addr.s6_addr + 12, sizeof ip);
+        snprintf(s, l, "%u", ntohl(ip));
```
Comment (thommey) [inline src/net.c]: should be "%" PRIu32

File: src/net.c [hunk 3]
```diff
@@ -1682,3 +1691,30 @@ char *traced_myiphostname(ClientData cd, Tcl_Interp *irp, EGG_CONST char *name1,
...
+  const char *value;
+  int r;
+  struct in_addr ia;
+
+  value = Tcl_GetVar2(irp, name1, name2, TCL_GLOBAL_ONLY);
+  if (*value) {
+    r = inet_pton(AF_INET, value, &ia);
+    if (!r) {
+      if (!online_since)
+        fatal("ERROR: config file: nat-ip address was not parseable in AF_INET", 0);
```
Comment (vanosg) [inline src/net.c]: Let's make the error something a little more understandable to the average user. Maybe "ERROR: nat-ip not a valid IP address"

File: src/net.c [hunk 4]
```diff
@@ -1682,3 +1691,30 @@ char *traced_myiphostname(ClientData cd, Tcl_Interp *irp, EGG_CONST char *name1,
...
+      return "address was not parseable in AF_INET";
```
Comment (vanosg) [inline src/net.c]: same here, 'address was not a valid IP address'
